# Generated by Django 6.0.2 on 2026-03-17 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("centers", "0002_center_application_review_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subject_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subject_name", models.CharField(max_length=255)),
                ("subject_code", models.CharField(max_length=50, unique=True)),
                ("assigned_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coaching_center",
                    models.ForeignKey(
                        db_column="coaching_center_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="centers.coachingcenter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="academics.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        db_column="teacher_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
            },
        ),
        migrations.CreateModel(
            name="TeachingMaterial",
            fields=[
                ("material_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("material_title", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("video", "Video"),
                            ("image", "Image"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_path", models.TextField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_column="batch_id",
                        help_text="If set, material is scoped to this specific batch.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academics.batch",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="teaching.subject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        db_column="uploaded_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teaching_materials",
            },
        ),
        migrations.CreateModel(
            name="TeacherSubjectBatchAssignment",
            fields=[
                (
                    "assignment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        db_column="assigned_by_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_teacher_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        db_column="batch_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_assignments",
                        to="academics.batch",
                    ),
                ),
                (
                    "coaching_center",
                    models.ForeignKey(
                        db_column="coaching_center_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_assignments",
                        to="centers.coachingcenter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_assignments",
                        to="academics.course",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teacher_assignments",
                        to="teaching.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        db_column="teacher_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teacher_subject_batch_assignments",
                "unique_together": {("batch", "subject")},
            },
        ),
    ]
