# Generated by Django 6.0.2 on 2026-03-01 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role_name",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("super_admin_staff", "Super Admin Staff"),
                            ("coaching_admin", "Coaching Admin"),
                            ("coaching_manager", "Coaching Manager"),
                            ("coaching_staff", "Coaching Staff"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("llm", "LLM System"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("profile_image", models.CharField(blank=True, max_length=500)),
                ("bio", models.TextField(blank=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        db_column="role_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("email_verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_verification_tokens",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("profile_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "class_name",
                    models.CharField(blank=True, db_column="class", max_length=50),
                ),
                ("group_name", models.CharField(blank=True, max_length=50)),
                ("roll_number", models.CharField(blank=True, max_length=50)),
                ("guardian_name", models.CharField(blank=True, max_length=255)),
                ("guardian_phone", models.CharField(blank=True, max_length=20)),
                (
                    "subject_specialization",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("experience_years", models.IntegerField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
    ]
