# Generated by Django 6.0.2 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(
                choices=[
                    ('coaching_admin', 'Coaching Admin'),
                    ('coaching_manager', 'Coaching Manager'),
                    ('coaching_staff', 'Coaching Staff'),
                    ('teacher', 'Teacher'),
                    ('student', 'Student'),
                    ('llm', 'LLM System'),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
