# Generated by Django 6.0.2 on 2026-03-17 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centers", "0002_center_application_review_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("course_title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in weeks"),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coaching_center",
                    models.ForeignKey(
                        db_column="coaching_center_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="centers.coachingcenter",
                    ),
                ),
            ],
            options={
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("batch_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("batch_name", models.CharField(max_length=255)),
                ("batch_code", models.CharField(max_length=50, unique=True)),
                (
                    "batch_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("crash", "Crash"),
                            ("online", "Online"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "class_shift",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("day", "Day"),
                            ("evening", "Evening"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("max_students", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coaching_center",
                    models.ForeignKey(
                        db_column="coaching_center_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="centers.coachingcenter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "db_table": "batches",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "enrollment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        db_column="batch_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="academics.batch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "unique_together": {("batch", "student")},
            },
        ),
    ]
