# Generated by Django 6.0.2 on 2026-03-17 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("teaching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("regular", "Regular"), ("live_quiz", "Live Quiz")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "pass_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("access_code", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        db_column="batch_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="academics.batch",
                    ),
                ),
                (
                    "host_teacher",
                    models.ForeignKey(
                        db_column="host_teacher_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="teaching.subject",
                    ),
                ),
            ],
            options={
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                ("question_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("true_false", "True/False"),
                            ("mcq", "MCQ"),
                            ("descriptive", "Descriptive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("max_marks", models.PositiveIntegerField(default=1)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("llm", "LLM")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("option_a", models.TextField(blank=True)),
                ("option_b", models.TextField(blank=True)),
                ("option_c", models.TextField(blank=True)),
                ("option_d", models.TextField(blank=True)),
                ("correct_option", models.CharField(blank=True, max_length=1)),
                ("expected_answer", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="teaching.subject",
                    ),
                ),
            ],
            options={
                "db_table": "question_bank",
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                ("result_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "total_marks_obtained",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("grade", models.CharField(blank=True, max_length=10)),
                (
                    "result_status",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail")], max_length=10
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exam_results",
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "exam_question_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("question_order", models.PositiveIntegerField(default=1)),
                (
                    "question_marks",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_slots",
                        to="exams.exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_mappings",
                        to="exams.questionbank",
                    ),
                ),
            ],
            options={
                "db_table": "exam_questions",
                "ordering": ("question_order",),
                "unique_together": {("exam", "question")},
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                ("answer_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("selected_option", models.CharField(blank=True, max_length=1)),
                ("descriptive_answer", models.TextField(blank=True)),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "answer_status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("submitted", "Submitted"),
                            ("checked", "Checked"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="evaluated_by_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluated_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="exams.exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_answers",
                        to="exams.questionbank",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_answers",
                "unique_together": {("exam", "student", "question")},
            },
        ),
    ]
