# Generated by Django 6.0.2 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMEvaluationLog",
            fields=[
                (
                    "evaluation_log_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("scoring_rubric", models.TextField()),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("feedback", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "llm_evaluation_logs",
            },
        ),
    ]
