# Generated by Django 6.0.2 on 2026-03-17 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_engine", "0001_initial"),
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llmevaluationlog",
            name="answer",
            field=models.ForeignKey(
                db_column="answer_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluation_logs",
                to="exams.studentanswer",
            ),
        ),
        migrations.AddField(
            model_name="llmevaluationlog",
            name="llm_user",
            field=models.ForeignKey(
                db_column="llm_user_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="llm_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="llmevaluationlog",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluation_logs",
                to="exams.questionbank",
            ),
        ),
    ]
