# Generated by Django 6.0.2 on 2026-03-16 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachingCenter",
            fields=[
                (
                    "coaching_center_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("center_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="center_logos/"),
                ),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid")],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "coaching_centers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CenterMembership",
            fields=[
                (
                    "membership_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("staff", "Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="center_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coaching_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="centers.coachingcenter",
                    ),
                ),
            ],
            options={
                "db_table": "center_memberships",
                "unique_together": {("user", "coaching_center")},
            },
        ),
    ]
